# Generated by Django 5.2.5 on 2025-08-29 13:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('startDate', models.DateField(default=django.utils.timezone.now)),
                ('endDate', models.DateField(default=django.utils.timezone.now)),
                ('amountSaved', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
