# Generated by Django 5.2.5 on 2025-08-31 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_income_allocated_amount_income_savings_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='savings_goal',
            field=models.ForeignKey(blank=True, default='none', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.savings'),
        ),
    ]
