# Generated by Django 5.2.5 on 2025-09-03 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_expense_user_income_user_savings_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='user',
        ),
        migrations.RemoveField(
            model_name='income',
            name='user',
        ),
        migrations.RemoveField(
            model_name='savings',
            name='user',
        ),
    ]
